### ISSUE TITLE
Consensus error reported from validator using Gaia v9.0.x

### ISSUE THREAD

**Issue by mmulji-ic** [informalsystems/tendermint#20]
Validator reported the following [consensus error](https://pastebin.com/AjJZUrVP). Currently waiting for additional infomation/logs.

**Tendermint version**:
`0.34.26` 

**Gaia version**:
`9.0.x` waiting for exact version, therefore this is `v9.0.0` or `v9.0.1`.

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
Application stopped validating blocks. Validator jailed.

**What you expected to happen**:
No error.

**Have you tried the latest version**: yes/no
no

**How to reproduce it** (as minimally and precisely as possible):
Unknown

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
https://pastebin.com/AjJZUrVP

**Config (you can paste only the changes you've made)**:
Waiting for more information.

**node command runtime flags**:
Waiting for more information.

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**
Asked, waiting for more information.

**Anything else we need to know**:

**Comment by thanethomson** [comment]
This fork is no longer supported - please log this issue on the CometBFT repo?

**Comment by mmulji-ic** [comment]
Issue moved to Comet repo https://github.com/cometbft/cometbft/issues/580
Closing here, unsupported fork.
